/**
 * AddRemoveCart - Recording Playback Tests
 *
 * Auto-generated by ATG from user recording
 * Total Steps: 5
 * Execution: Sequential flow (all CPs share the same page/session)
 *
 * @generated
 */

import 'dotenv/config';
import { test, expect } from '@playwright/test';

test.describe('AddRemoveCart - Recording Playback', () => {

  test('AddRemoveCart - Sequential Flow', async ({ page }) => {

    // ═══ LOGIN (inline) ═══
    // CP1: Validar que la URL de inicio de sesión responde correctamente
    await test.step('CP1: Login page loads successfully', async () => {
      const loginUrl = process.env.LOGIN_URL || '';
      expect.soft(loginUrl, 'LOGIN_URL must be defined in .env').not.toBe('');
      if (!loginUrl) return;
      await page.goto(loginUrl, { waitUntil: 'domcontentloaded' });
      await expect.soft(page).not.toHaveURL(/about:blank/);
    });

    // CP2: Validar que se inicia sesión correctamente
    await test.step('CP2: Login is successful', async () => {
      const loginUrl = process.env.LOGIN_URL || '';
      expect.soft(loginUrl, 'LOGIN_URL must be defined in .env').not.toBe('');
      if (!loginUrl) return;
      await page.goto(loginUrl, { waitUntil: 'domcontentloaded' });
      await page.locator('input[type="text"], input[name="username"], input[id="username"]').first().fill(process.env.TEST_USER_ADMIN_USERNAME || '');
      await page.locator('input[type="password"]').first().fill(process.env.TEST_USER_ADMIN_PASSWORD || '');
      await page.locator('button[type="submit"], input[type="submit"], button:has-text("Login"), button:has-text("Sign in")').first().click();
      await page.waitForLoadState('networkidle');
      // Validate URL changed away from login page
      expect.soft(page.url()).not.toBe(loginUrl);
    });

    // ═══ TEST BANK CPs ═══

    // CP3: URL responde correctamente
    await test.step('CP3: URL responde correctamente', async () => {
      // Navigate and verify page loads
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      await expect(page).not.toHaveURL(/about:blank/);
      expect(page.url()).toContain(new URL('https://www.saucedemo.com/inventory.html').pathname);
    });

    // CP4: Login exitoso
    await test.step('CP4: Login exitoso', async () => {
      // Already logged in via storageState
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      const loginUrl = process.env.LOGIN_URL || '';
      expect.soft(page.url()).not.toBe(loginUrl);
    });

    // CP5: Tiempo de carga base
    await test.step('CP5: Tiempo de carga base', async () => {
      const loadStart = Date.now();
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      const loadTime = Date.now() - loadStart;
      expect(loadTime).toBeLessThan(15000);
    });

    // CP6: Sin requests fallidos en red
    await test.step('CP6: Sin requests fallidos en red', async () => {
      const failedRequests: { url: string; status: number }[] = [];
      page.on('response', response => {
      const status = response.status();
      const url = response.url();
      if (status >= 400 && !url.includes('favicon') && !url.includes('analytics') && !url.includes('gtag') && !url.includes('hotjar')) {
      failedRequests.push({ url, status });
      }
      });
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      expect(failedRequests, `Failed requests: ${JSON.stringify(failedRequests)}`).toHaveLength(0);
    });

    // CP7: Title y favicon cargan
    await test.step('CP7: Title y favicon cargan', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check title and favicon
      const title = await page.title();
      expect(title).not.toBe('');
    });

    // CP8: Sin contenido de error genérico
    await test.step('CP8: Sin contenido de error genérico', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check for error elements
      const errorMessages = page.locator(".error, [class*=\"error\"], [class*=\"alert\"]").filter({ hasNot: page.locator("input, select, textarea") }).filter({ hasText: /.+/ });
      await expect(errorMessages.first()).not.toBeVisible();
    });

    // CP9: Sin errores en consola
    await test.step('CP9: Sin errores en consola', async () => {
      const consoleErrors: string[] = [];
      page.on('console', msg => {
      if (msg.type() === 'error') {
      consoleErrors.push(msg.text());
      }
      });
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      const criticalErrors = consoleErrors.filter(e =>
      !e.includes('favicon') &&
      !e.includes('404') &&
      !e.includes('deprecated') &&
      !e.includes('downloadable font') &&
      !e.includes('font-family') &&
      !e.includes('DM Sans') &&
      !e.includes('DM Mono') &&
      !e.includes('service worker')
      );
      expect(criticalErrors).toHaveLength(0);
    });

    // CP10: Layout base existe
    await test.step('CP10: Layout base existe', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Inspect page structure
      const mainContent = page.locator('main, [role="main"], .content, #content, #app, #root').first();
      await expect(mainContent).toBeAttached();
    });

    // CP11: Contenedor principal no vacío
    await test.step('CP11: Contenedor principal no vacío', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check main content area
      const container = page.locator('main, [role="main"], .content, #content, #app, #root').first();
      await expect(container).not.toBeEmpty();
    });

    // CP12: Sin placeholders eternos
    await test.step('CP12: Sin placeholders eternos', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      await page.waitForTimeout(2000);
      const placeholders = page.locator('.skeleton, .loading, [class*="spinner"], [class*="skeleton"]').filter({ hasText: /.*/});
      const count = await placeholders.count();
      for (let i = 0; i < count; i++) {
      await expect(placeholders.nth(i)).not.toBeVisible();
      }
    });

    // CP13: Idioma por defecto
    await test.step('CP13: Idioma por defecto', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check html lang attribute
      const lang = await page.getAttribute('html', 'lang');
      expect(lang).toBeTruthy();
    });

    // CP14: Sin overlays bloqueantes
    await test.step('CP14: Sin overlays bloqueantes', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      await page.waitForTimeout(1000);
      const overlays = page.locator('.modal, .overlay, [class*="modal"], [class*="overlay"], [role="dialog"]').filter({ hasText: /.+/ });
      const count = await overlays.count();
      let blockingCount = 0;
      for (let i = 0; i < count; i++) {
      const isVisible = await overlays.nth(i).isVisible().catch(() => false);
      if (isVisible) blockingCount++;
      }
      expect(blockingCount).toBe(0);
    });

    // CP15: Sin scroll horizontal
    await test.step('CP15: Sin scroll horizontal', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check horizontal overflow
      const hasHorizontalScroll = await page.evaluate(() =>
      document.documentElement.scrollWidth > document.documentElement.clientWidth
      );
      expect(hasHorizontalScroll).toBe(false);
    });

    // CP16: Sin elementos superpuestos
    await test.step('CP16: Sin elementos superpuestos', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Check element bounding boxes
      const hasOverlap = await page.evaluate(() => {
      const header = document.querySelector('header, [role="banner"], nav');
      const main = document.querySelector('main, [role="main"], .content, #content');
      if (!header || !main) return false;
      const headerRect = header.getBoundingClientRect();
      const mainRect = main.getBoundingClientRect();
      const overlapY = Math.max(0, Math.min(headerRect.bottom, mainRect.bottom) - Math.max(headerRect.top, mainRect.top));
      const headerHeight = headerRect.height || 1;
      return overlapY / headerHeight > 0.5;
      });
      expect(hasOverlap).toBe(false);
    });

    // CP17: CPR1: Screenshot baseline
    await test.step('CP17: CPR1: Screenshot baseline', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      await page.waitForTimeout(1000);
      await page.screenshot({ path: `screenshots/baseline-${test.info().titlePath.join('-').replace(/[^a-zA-Z0-9-]/g, '_')}.png`, fullPage: true });
    });

    // CP18: CPR2: Conteo de elementos clave estable
    await test.step('CP18: CPR2: Conteo de elementos clave estable', async () => {
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      // Count key elements
      const container = page.locator('main, [role="main"], .content, #content, #app, #root').first();
      const childCount = await container.locator('> *').count();
      expect(childCount).toBeGreaterThan(0);
    });

    // CP19: CPR3: Sin nuevos warnings/errors severos
    await test.step('CP19: CPR3: Sin nuevos warnings/errors severos', async () => {
      const consoleMessages: { type: string; text: string }[] = [];
      page.on('console', msg => {
      if (msg.type() === 'error' || msg.type() === 'warning') {
      consoleMessages.push({ type: msg.type(), text: msg.text() });
      }
      });
      const targetUrl = 'https://www.saucedemo.com/inventory.html';
      const targetPath = new URL(targetUrl).pathname;
      if (!page.url().includes(targetPath)) {
      await page.goto(targetUrl, { waitUntil: 'domcontentloaded' });
      }
      const severeMessages = consoleMessages.filter(m =>
      m.type === 'error' &&
      !m.text.includes('favicon') &&
      !m.text.includes('404') &&
      !m.text.includes('deprecated') &&
      !m.text.includes('third-party') &&
      !m.text.includes('downloadable font') &&
      !m.text.includes('font-family') &&
      !m.text.includes('DM Sans') &&
      !m.text.includes('DM Mono') &&
      !m.text.includes('service worker')
      );
      expect(severeMessages).toHaveLength(0);
    });

    // ═══ RECORDING ELEMENT CPs (8 per element) ═══

    // CP20: Validar que [data test="add to cart sauce labs backpack"] está presente
    await test.step('CP20: [data test="add to cart sauce labs backpack"] is visible', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-backpack"]');
      await expect.soft(element).toBeVisible();
    });

    // CP21: Initial state for [data test="add to cart sauce labs backpack"]
    await test.step('CP21: Initial state', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-backpack"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const type = (await element.getAttribute('type')) || '';
      if (tag === 'input' && (type === 'checkbox' || type === 'radio')) {
        await expect.soft(element).not.toBeChecked();
      } else if (tag === 'input' || tag === 'textarea' || tag === 'select') {
        await expect.soft(element).toBeEnabled();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP22: Interactable check for [data test="add to cart sauce labs backpack"]
    await test.step('CP22: Interactable', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-backpack"]');
      const interactable = await element.evaluate(e => { const style = window.getComputedStyle(e); return style.pointerEvents !== 'none' && style.display !== 'none' && style.visibility !== 'hidden'; });
      await expect.soft(interactable).toBeTruthy();
    });

    // CP23: Focus check for [data test="add to cart sauce labs backpack"]
    await test.step('CP23: Focus', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-backpack"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const tabindex = await element.getAttribute('tabindex');
      const isFocusable = ['input','textarea','select','a','button'].includes(tag) || tabindex !== null;
      if (isFocusable) {
        await element.focus();
        await expect.soft(element).toBeFocused();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP24: Click [data test="add to cart sauce labs backpack"]
    await test.step('CP24: Click [data test="add to cart sauce labs backpack"]', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-backpack"]');
      await expect.soft(element).toBeVisible();
      await element.click();
    });

    // CP25: No inconsistent/stuck state after [data test="add to cart sauce labs backpack"]
    await test.step('CP25: Stable state after action', async () => {
      const spinners = page.locator('.spinner, .loading, [class*="spinner"], [class*="loading"]');
      await expect.soft(spinners.first()).not.toBeVisible();
    });

    // CP26: Validar que no hay errores visibles después de la acción
    await test.step('CP26: No visible errors after [data test="add to cart sauce labs backpack"]', async () => {
      const errorMessages = page.locator('.error, [class*="error"], [class*="alert"]').filter({ hasNot: page.locator('input, select, textarea') }).filter({ hasText: /.+/ });
      await expect.soft(errorMessages.first(), 'No visible errors after [data test="add to cart sauce labs backpack"]').not.toBeVisible();
    });

    // CP27: Validar que no hay errores de consola después de la acción
    await test.step('CP27: No console errors after [data test="add to cart sauce labs backpack"]', async () => {
      const consoleErrors: string[] = [];
      const handler = (msg: any) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); };
      page.on('console', handler);
      await page.waitForTimeout(500);
      page.removeListener('console', handler);
      const criticalErrors = consoleErrors.filter(e => 
        !e.includes('favicon') && 
        !e.includes('404') && 
        !e.includes('deprecated') &&
        !e.includes('401') &&
        !e.includes('unauthorized') &&
        !e.includes('downloadable font')
      );
      expect.soft(criticalErrors, 'No console errors after [data test="add to cart sauce labs backpack"]').toHaveLength(0);
    });

    // CP28: Validar que [data test="remove sauce labs backpack"] está presente
    await test.step('CP28: [data test="remove sauce labs backpack"] is visible', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-backpack"]');
      await expect.soft(element).toBeVisible();
    });

    // CP29: Initial state for [data test="remove sauce labs backpack"]
    await test.step('CP29: Initial state', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-backpack"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const type = (await element.getAttribute('type')) || '';
      if (tag === 'input' && (type === 'checkbox' || type === 'radio')) {
        await expect.soft(element).not.toBeChecked();
      } else if (tag === 'input' || tag === 'textarea' || tag === 'select') {
        await expect.soft(element).toBeEnabled();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP30: Interactable check for [data test="remove sauce labs backpack"]
    await test.step('CP30: Interactable', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-backpack"]');
      const interactable = await element.evaluate(e => { const style = window.getComputedStyle(e); return style.pointerEvents !== 'none' && style.display !== 'none' && style.visibility !== 'hidden'; });
      await expect.soft(interactable).toBeTruthy();
    });

    // CP31: Focus check for [data test="remove sauce labs backpack"]
    await test.step('CP31: Focus', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-backpack"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const tabindex = await element.getAttribute('tabindex');
      const isFocusable = ['input','textarea','select','a','button'].includes(tag) || tabindex !== null;
      if (isFocusable) {
        await element.focus();
        await expect.soft(element).toBeFocused();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP32: Click [data test="remove sauce labs backpack"]
    await test.step('CP32: Click [data test="remove sauce labs backpack"]', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-backpack"]');
      await expect.soft(element).toBeVisible();
      await element.click();
    });

    // CP33: No inconsistent/stuck state after [data test="remove sauce labs backpack"]
    await test.step('CP33: Stable state after action', async () => {
      const spinners = page.locator('.spinner, .loading, [class*="spinner"], [class*="loading"]');
      await expect.soft(spinners.first()).not.toBeVisible();
    });

    // CP34: Validar que no hay errores visibles después de la acción
    await test.step('CP34: No visible errors after [data test="remove sauce labs backpack"]', async () => {
      const errorMessages = page.locator('.error, [class*="error"], [class*="alert"]').filter({ hasNot: page.locator('input, select, textarea') }).filter({ hasText: /.+/ });
      await expect.soft(errorMessages.first(), 'No visible errors after [data test="remove sauce labs backpack"]').not.toBeVisible();
    });

    // CP35: Validar que no hay errores de consola después de la acción
    await test.step('CP35: No console errors after [data test="remove sauce labs backpack"]', async () => {
      const consoleErrors: string[] = [];
      const handler = (msg: any) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); };
      page.on('console', handler);
      await page.waitForTimeout(500);
      page.removeListener('console', handler);
      const criticalErrors = consoleErrors.filter(e => 
        !e.includes('favicon') && 
        !e.includes('404') && 
        !e.includes('deprecated') &&
        !e.includes('401') &&
        !e.includes('unauthorized') &&
        !e.includes('downloadable font')
      );
      expect.soft(criticalErrors, 'No console errors after [data test="remove sauce labs backpack"]').toHaveLength(0);
    });

    // CP36: Validar que [data test="add to cart sauce labs bike light"] está presente
    await test.step('CP36: [data test="add to cart sauce labs bike light"] is visible', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]');
      await expect.soft(element).toBeVisible();
    });

    // CP37: Initial state for [data test="add to cart sauce labs bike light"]
    await test.step('CP37: Initial state', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const type = (await element.getAttribute('type')) || '';
      if (tag === 'input' && (type === 'checkbox' || type === 'radio')) {
        await expect.soft(element).not.toBeChecked();
      } else if (tag === 'input' || tag === 'textarea' || tag === 'select') {
        await expect.soft(element).toBeEnabled();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP38: Interactable check for [data test="add to cart sauce labs bike light"]
    await test.step('CP38: Interactable', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]');
      const interactable = await element.evaluate(e => { const style = window.getComputedStyle(e); return style.pointerEvents !== 'none' && style.display !== 'none' && style.visibility !== 'hidden'; });
      await expect.soft(interactable).toBeTruthy();
    });

    // CP39: Focus check for [data test="add to cart sauce labs bike light"]
    await test.step('CP39: Focus', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const tabindex = await element.getAttribute('tabindex');
      const isFocusable = ['input','textarea','select','a','button'].includes(tag) || tabindex !== null;
      if (isFocusable) {
        await element.focus();
        await expect.soft(element).toBeFocused();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP40: Click [data test="add to cart sauce labs bike light"]
    await test.step('CP40: Click [data test="add to cart sauce labs bike light"]', async () => {
      const element = page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]');
      await expect.soft(element).toBeVisible();
      await element.click();
    });

    // CP41: No inconsistent/stuck state after [data test="add to cart sauce labs bike light"]
    await test.step('CP41: Stable state after action', async () => {
      const spinners = page.locator('.spinner, .loading, [class*="spinner"], [class*="loading"]');
      await expect.soft(spinners.first()).not.toBeVisible();
    });

    // CP42: Validar que no hay errores visibles después de la acción
    await test.step('CP42: No visible errors after [data test="add to cart sauce labs bike light"]', async () => {
      const errorMessages = page.locator('.error, [class*="error"], [class*="alert"]').filter({ hasNot: page.locator('input, select, textarea') }).filter({ hasText: /.+/ });
      await expect.soft(errorMessages.first(), 'No visible errors after [data test="add to cart sauce labs bike light"]').not.toBeVisible();
    });

    // CP43: Validar que no hay errores de consola después de la acción
    await test.step('CP43: No console errors after [data test="add to cart sauce labs bike light"]', async () => {
      const consoleErrors: string[] = [];
      const handler = (msg: any) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); };
      page.on('console', handler);
      await page.waitForTimeout(500);
      page.removeListener('console', handler);
      const criticalErrors = consoleErrors.filter(e => 
        !e.includes('favicon') && 
        !e.includes('404') && 
        !e.includes('deprecated') &&
        !e.includes('401') &&
        !e.includes('unauthorized') &&
        !e.includes('downloadable font')
      );
      expect.soft(criticalErrors, 'No console errors after [data test="add to cart sauce labs bike light"]').toHaveLength(0);
    });

    // CP44: Validar que [data test="remove sauce labs bike light"] está presente
    await test.step('CP44: [data test="remove sauce labs bike light"] is visible', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-bike-light"]');
      await expect.soft(element).toBeVisible();
    });

    // CP45: Initial state for [data test="remove sauce labs bike light"]
    await test.step('CP45: Initial state', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-bike-light"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const type = (await element.getAttribute('type')) || '';
      if (tag === 'input' && (type === 'checkbox' || type === 'radio')) {
        await expect.soft(element).not.toBeChecked();
      } else if (tag === 'input' || tag === 'textarea' || tag === 'select') {
        await expect.soft(element).toBeEnabled();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP46: Interactable check for [data test="remove sauce labs bike light"]
    await test.step('CP46: Interactable', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-bike-light"]');
      const interactable = await element.evaluate(e => { const style = window.getComputedStyle(e); return style.pointerEvents !== 'none' && style.display !== 'none' && style.visibility !== 'hidden'; });
      await expect.soft(interactable).toBeTruthy();
    });

    // CP47: Focus check for [data test="remove sauce labs bike light"]
    await test.step('CP47: Focus', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-bike-light"]');
      const tag = await element.evaluate(e => (e.tagName || '').toLowerCase());
      const tabindex = await element.getAttribute('tabindex');
      const isFocusable = ['input','textarea','select','a','button'].includes(tag) || tabindex !== null;
      if (isFocusable) {
        await element.focus();
        await expect.soft(element).toBeFocused();
      } else {
        await expect.soft(element).toBeVisible();
      }
    });

    // CP48: Click [data test="remove sauce labs bike light"]
    await test.step('CP48: Click [data test="remove sauce labs bike light"]', async () => {
      const element = page.locator('[data-test="remove-sauce-labs-bike-light"]');
      await expect.soft(element).toBeVisible();
      await element.click();
    });

    // CP49: No inconsistent/stuck state after [data test="remove sauce labs bike light"]
    await test.step('CP49: Stable state after action', async () => {
      const spinners = page.locator('.spinner, .loading, [class*="spinner"], [class*="loading"]');
      await expect.soft(spinners.first()).not.toBeVisible();
    });

    // CP50: Validar que no hay errores visibles después de la acción
    await test.step('CP50: No visible errors after [data test="remove sauce labs bike light"]', async () => {
      const errorMessages = page.locator('.error, [class*="error"], [class*="alert"]').filter({ hasNot: page.locator('input, select, textarea') }).filter({ hasText: /.+/ });
      await expect.soft(errorMessages.first(), 'No visible errors after [data test="remove sauce labs bike light"]').not.toBeVisible();
    });

    // CP51: Validar que no hay errores de consola después de la acción
    await test.step('CP51: No console errors after [data test="remove sauce labs bike light"]', async () => {
      const consoleErrors: string[] = [];
      const handler = (msg: any) => { if (msg.type() === 'error') consoleErrors.push(msg.text()); };
      page.on('console', handler);
      await page.waitForTimeout(500);
      page.removeListener('console', handler);
      const criticalErrors = consoleErrors.filter(e => 
        !e.includes('favicon') && 
        !e.includes('404') && 
        !e.includes('deprecated') &&
        !e.includes('401') &&
        !e.includes('unauthorized') &&
        !e.includes('downloadable font')
      );
      expect.soft(criticalErrors, 'No console errors after [data test="remove sauce labs bike light"]').toHaveLength(0);
    });

  });

});